// A tiny software rasteriser. No graphics framework is available off-Apple, but
// the meshes, the rig and the animator are all ours — so we can walk the entity
// tree, project the triangles ourselves and actually look at the cat.
// Run with `--render`.
import Foundation
import RealityKit

/// Builds the cat the app would ship — the modelled one — falling back to the
/// generated one when the export is not present.
///
/// The app finds the asset in its bundle. There is no bundle here, so the file is
/// read from the source tree; the point of this renderer is to look at what the
/// player will look at, and since the port that is a skinned mesh rather than
/// thirty lofts.
private let shippedAsset: CatMeshAsset? = {
    guard let d = FileManager.default.contents(atPath: "MeowRoom/Resources/cat.catmesh")
    else { return nil }
    return try? CatMeshAsset(data: d)
}()

private func buildCat(_ a: CatAppearance, preview: Bool = false) -> CatRig {
    if let asset = shippedAsset { return CatBuilder.build(a, preview: preview, using: asset) }
    return CatBuilder.build(a, preview: preview)
}

// MARK: - Triangle soup

private struct Tri {
    var a: SIMD3<Float>
    var b: SIMD3<Float>
    var c: SIMD3<Float>
    var shade: Float          // material lightness 0…1
}

/// The triangles an entity draws, in its own space.
///
/// This used to have a second half: a hand-written tessellator for `SCNBox`,
/// `SCNCylinder`, `SCNTorus` and the rest, because the room was built from
/// SceneKit primitives whose vertices only existed inside the renderer. All of
/// that is gone — every shape in the game is now generated by `MeshBuilder`, so
/// there is exactly one path, and the offline renderer draws the same buffers
/// that get uploaded to the GPU rather than an approximation of them.
private func tessellate(_ entity: Entity) -> ([SIMD3<Float>], [Int32])? {
    guard let resource = (entity as? ModelEntity)?.model?.mesh,
          let mesh = MeshSourceRegistry.mesh(for: resource),
          !mesh.indices.isEmpty else { return nil }
    return (mesh.positions.map { SIMD3<Float>(x: $0.x, y: $0.y, z: $0.z) }, mesh.indices)
}

/// Transforms a point by a world matrix.
private func apply(_ m: simd_float4x4, _ p: SIMD3<Float>) -> SIMD3<Float> {
    let v = m * SIMD4<Float>(p.x, p.y, p.z, 1)
    return SIMD3<Float>(v.x, v.y, v.z)
}

private func gather(_ entity: Entity, into tris: inout [Tri], skipHidden: Bool = true) {
    if skipHidden && !entity.isEnabled { return }
    if let (verts, idx) = tessellate(entity) {
        let world = entity.worldMatrix
        // Approximate the material by its base colour's lightness.
        var shade: Float = 0.65
        if let tint = entity.pbrMaterial?.baseColor.tint {
            var r: CGFloat = 0, g: CGFloat = 0, b: CGFloat = 0, a: CGFloat = 0
            tint.getRed(&r, green: &g, blue: &b, alpha: &a)
            shade = Float(0.2126 * r + 0.7152 * g + 0.0722 * b)
            if shade < 0.02 { shade = 0.55 }   // shim colours read back as black
        }
        var i = 0
        while i + 2 < idx.count {
            let a = apply(world, verts[Int(idx[i])])
            let b = apply(world, verts[Int(idx[i + 1])])
            let c = apply(world, verts[Int(idx[i + 2])])
            tris.append(Tri(a: a, b: b, c: c, shade: shade))
            i += 3
        }
    }
    for child in entity.children { gather(child, into: &tris, skipHidden: skipHidden) }
}

// MARK: - Rasteriser

private func render(_ tris: [Tri],
                    eye: SIMD3<Float>, target: SIMD3<Float>,
                    fovDegrees: Float, width: Int, height: Int,
                    background: (Float, Float, Float)) -> [UInt8] {
    // Camera basis.
    let forward = (target - eye).normalized
    let worldUp = SIMD3<Float>(x: 0, y: 1, z: 0)
    var right = cross(worldUp, forward).normalized
    if right.length < 1e-4 { right = SIMD3<Float>(x: 1, y: 0, z: 0) }
    let up = cross(forward, right).normalized

    let aspect = Float(width) / Float(height)
    let tanHalf = tanf(fovDegrees * .pi / 180 / 2)

    var depth = [Float](repeating: .greatestFiniteMagnitude, count: width * height)
    var pixels = [UInt8](repeating: 0, count: width * height * 3)
    for i in 0..<(width * height) {
        pixels[i * 3] = UInt8(clamp(background.0) * 255)
        pixels[i * 3 + 1] = UInt8(clamp(background.1) * 255)
        pixels[i * 3 + 2] = UInt8(clamp(background.2) * 255)
    }

    let lightDir = SIMD3<Float>(x: -0.45, y: 0.8, z: -0.4).normalized

    for tri in tris {
        // To camera space.
        func toCamera(_ p: SIMD3<Float>) -> SIMD3<Float> {
            let d = p - eye
            return SIMD3<Float>(x: dot(d, right), y: dot(d, up), z: dot(d, forward))
        }
        let ca = toCamera(tri.a), cb = toCamera(tri.b), cc = toCamera(tri.c)
        guard ca.z > 0.02, cb.z > 0.02, cc.z > 0.02 else { continue }

        func project(_ p: SIMD3<Float>) -> (Float, Float) {
            let x = (p.x / (p.z * tanHalf * aspect) * 0.5 + 0.5) * Float(width)
            let y = (1 - (p.y / (p.z * tanHalf) * 0.5 + 0.5)) * Float(height)
            return (x, y)
        }
        let (x0, y0) = project(ca), (x1, y1) = project(cb), (x2, y2) = project(cc)

        let normal = cross(tri.b - tri.a, tri.c - tri.a).normalized
        let lambert = max(0.12, dot(normal, lightDir))
        let value = clamp(tri.shade * (0.28 + 0.85 * lambert))

        let minX = max(0, Int(floor(min(x0, x1, x2))))
        let maxX = min(width - 1, Int(ceil(max(x0, x1, x2))))
        let minY = max(0, Int(floor(min(y0, y1, y2))))
        let maxY = min(height - 1, Int(ceil(max(y0, y1, y2))))
        if minX > maxX || minY > maxY { continue }

        let area = (x1 - x0) * (y2 - y0) - (x2 - x0) * (y1 - y0)
        if abs(area) < 1e-8 { continue }

        for py in minY...maxY {
            for px in minX...maxX {
                let fx = Float(px) + 0.5, fy = Float(py) + 0.5
                var w0 = ((x1 - fx) * (y2 - fy) - (x2 - fx) * (y1 - fy)) / area
                var w1 = ((x2 - fx) * (y0 - fy) - (x0 - fx) * (y2 - fy)) / area
                var w2 = 1 - w0 - w1
                if area < 0 { w0 = -w0; w1 = -w1; w2 = -w2 }
                guard w0 >= -1e-5, w1 >= -1e-5, w2 >= -1e-5 else { continue }
                let z = abs(w0) * ca.z + abs(w1) * cb.z + abs(w2) * cc.z
                let o = py * width + px
                guard z < depth[o] else { continue }
                depth[o] = z
                let v = UInt8(clamp(value) * 255)
                pixels[o * 3] = v
                pixels[o * 3 + 1] = UInt8(clamp(value * 0.98) * 255)
                pixels[o * 3 + 2] = UInt8(clamp(value * 0.94) * 255)
            }
        }
    }
    return pixels
}

// MARK: - PNG

private func writePNG(_ pixels: [UInt8], width: Int, height: Int, to path: String) {
    var raw = [UInt8]()
    raw.reserveCapacity(height * (1 + width * 3))
    for y in 0..<height {
        raw.append(0)
        raw.append(contentsOf: pixels[(y * width * 3)..<((y + 1) * width * 3)])
    }

    func crc32(_ data: [UInt8]) -> UInt32 {
        var table = [UInt32](repeating: 0, count: 256)
        for i in 0..<256 {
            var c = UInt32(i)
            for _ in 0..<8 { c = (c & 1) != 0 ? 0xEDB88320 ^ (c >> 1) : c >> 1 }
            table[i] = c
        }
        var c: UInt32 = 0xFFFFFFFF
        for byte in data { c = table[Int((c ^ UInt32(byte)) & 0xFF)] ^ (c >> 8) }
        return c ^ 0xFFFFFFFF
    }

    func adler32(_ data: [UInt8]) -> UInt32 {
        var a: UInt32 = 1, b: UInt32 = 0
        for byte in data {
            a = (a + UInt32(byte)) % 65521
            b = (b + a) % 65521
        }
        return (b << 16) | a
    }

    func be32(_ v: UInt32) -> [UInt8] {
        [UInt8((v >> 24) & 0xFF), UInt8((v >> 16) & 0xFF), UInt8((v >> 8) & 0xFF), UInt8(v & 0xFF)]
    }

    func chunk(_ tag: String, _ payload: [UInt8]) -> [UInt8] {
        let tagBytes = Array(tag.utf8)
        return be32(UInt32(payload.count)) + tagBytes + payload + be32(crc32(tagBytes + payload))
    }

    // zlib stream with stored (uncompressed) deflate blocks.
    var z: [UInt8] = [0x78, 0x01]
    var offset = 0
    while offset < raw.count {
        let size = min(65535, raw.count - offset)
        let final: UInt8 = (offset + size >= raw.count) ? 1 : 0
        z.append(final)
        z.append(UInt8(size & 0xFF)); z.append(UInt8((size >> 8) & 0xFF))
        let inv = ~UInt16(size)
        z.append(UInt8(inv & 0xFF)); z.append(UInt8((inv >> 8) & 0xFF))
        z.append(contentsOf: raw[offset..<(offset + size)])
        offset += size
    }
    z += be32(adler32(raw))

    var png: [UInt8] = [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]
    png += chunk("IHDR", be32(UInt32(width)) + be32(UInt32(height)) + [8, 2, 0, 0, 0])
    png += chunk("IDAT", z)
    png += chunk("IEND", [])
    _ = FileManager.default.createFile(atPath: path, contents: Data(png))
}

// MARK: - Screen-space measurement

/// Where a node lands in the final frame, in points, using the same projection as
/// the rasteriser. The HUD occupies a fixed band along the bottom of the screen,
/// so knowing the cat's screen box is the only way to tell — without a Mac —
/// whether a cat that comes when called ends up hidden behind the status pill.
private func screenBounds(_ node: Entity,
                          eye: SIMD3<Float>, target: SIMD3<Float>,
                          fovDegrees: Float, width: Int, height: Int)
    -> (minX: Float, maxX: Float, minY: Float, maxY: Float)? {

    var tris: [Tri] = []
    gather(node, into: &tris)

    let forward = (target - eye).normalized
    var right = cross(SIMD3<Float>(x: 0, y: 1, z: 0), forward).normalized
    if right.length < 1e-4 { right = SIMD3<Float>(x: 1, y: 0, z: 0) }
    let up = cross(forward, right).normalized

    let aspect = Float(width) / Float(height)
    let tanHalf = tanf(fovDegrees * .pi / 180 / 2)

    var minX = Float.infinity, maxX = -Float.infinity
    var minY = Float.infinity, maxY = -Float.infinity
    var any = false

    for tri in tris {
        for p in [tri.a, tri.b, tri.c] {
            let d = p - eye
            let z = dot(d, forward)
            guard z > 0.02 else { continue }
            let x = (dot(d, right) / (z * tanHalf * aspect) * 0.5 + 0.5) * Float(width)
            let y = (1 - (dot(d, up) / (z * tanHalf) * 0.5 + 0.5)) * Float(height)
            minX = min(minX, x); maxX = max(maxX, x)
            minY = min(minY, y); maxY = max(maxY, y)
            any = true
        }
    }
    return any ? (minX, maxX, minY, maxY) : nil
}

// MARK: - Entry point

func runRender(outputDirectory: String) {
    // Only the render pass needs the generators' raw buffers kept around.
    MeshSourceRegistry.isRecording = true
    defer {
        MeshSourceRegistry.isRecording = false
        MeshSourceRegistry.reset()
    }

    let fm = FileManager.default
    try? fm.createDirectory(atPath: outputDirectory, withIntermediateDirectories: true)

    func shot(_ name: String, _ node: Entity, eye: SIMD3<Float>, target: SIMD3<Float>,
              fov: Float, size: (Int, Int), bg: (Float, Float, Float) = (0.10, 0.10, 0.12)) {
        var tris: [Tri] = []
        gather(node, into: &tris)
        let pixels = render(tris, eye: eye, target: target, fovDegrees: fov,
                            width: size.0, height: size.1, background: bg)
        writePNG(pixels, width: size.0, height: size.1, to: "\(outputDirectory)/\(name).png")
        var lo = SIMD3<Float>(x: .infinity, y: .infinity, z: .infinity)
        var hi = SIMD3<Float>(x: -.infinity, y: -.infinity, z: -.infinity)
        for t in tris {
            for p in [t.a, t.b, t.c] {
                lo = SIMD3<Float>(x: min(lo.x, p.x), y: min(lo.y, p.y), z: min(lo.z, p.z))
                hi = SIMD3<Float>(x: max(hi.x, p.x), y: max(hi.y, p.y), z: max(hi.z, p.z))
            }
        }
        print(String(format: "  %@.png  %d tris  bbox x[%.2f %.2f] y[%.2f %.2f] z[%.2f %.2f]",
                     name as NSString, tris.count, lo.x, hi.x, lo.y, hi.y, lo.z, hi.z))
    }

    print("rendering to \(outputDirectory)")

    // --- The cat, in a few poses, from the side and three-quarter.
    let poses: [(String, CatPose)] = [("stand", .standing), ("sit", .sittingTall),
                                      ("loaf", .loaf), ("curl", .curled),
                                      ("walk", .walking), ("stretch", .stretching)]
    for (label, pose) in poses {
        let appearance = BreedPresets.appearance(for: .domesticShorthair)
        let rig = buildCat(appearance)
        let animator = CatAnimator(rig: rig)
        var motion = CatMotion()
        motion.position = .zero
        motion.pose = pose
        motion.speed = pose.isLocomotion ? 0.6 : 0
        motion.eyeOpen = pose.isSleep ? 0.05 : 1
        for _ in 0..<300 { animator.update(dt: 1.0 / 60, motion: motion) }

        shot("cat-\(label)-side", rig.root,
             eye: SIMD3<Float>(x: 0.95, y: 0.20, z: 0.05), target: SIMD3<Float>(x: 0, y: 0.16, z: 0),
             fov: 34, size: (420, 320))
        shot("cat-\(label)-front", rig.root,
             eye: SIMD3<Float>(x: 0.30, y: 0.30, z: 0.85), target: SIMD3<Float>(x: 0, y: 0.16, z: 0),
             fov: 34, size: (420, 320))
    }

    // --- The head, close up. The game is mostly a face at close range, and the
    // ear/skull junction in particular is easy to get wrong: the ear roots sit
    // inside the skull, so if they drift out the ears read as floating.
    for breed in [CatBreed.domesticShorthair, .maineCoon, .persian, .siamese] {
        let a = BreedPresets.appearance(for: breed)
        let rig = buildCat(a)
        let animator = CatAnimator(rig: rig)
        var motion = CatMotion()
        motion.position = .zero
        motion.pose = .sittingTall
        for _ in 0..<200 { animator.update(dt: 1.0 / 60, motion: motion) }
        CatBuilder.syncPose(rig)

        let head = rig.head.convert(position: SIMD3<Float>(repeating: 0), to: nil)
        let d = a.headRadius * 11
        shot("head-\(breed.rawValue)-front", rig.root,
             eye: SIMD3<Float>(x: head.x, y: head.y + d * 0.16, z: head.z + d),
             target: head, fov: 30, size: (460, 460))
        shot("head-\(breed.rawValue)-threequarter", rig.root,
             eye: SIMD3<Float>(x: head.x + d * 0.62, y: head.y + d * 0.30, z: head.z + d * 0.72),
             target: head, fov: 30, size: (460, 460))

        // Mid-meow, jaw wide. Until recently there was nothing behind it and an open
        // mouth was a hole through the cat's face, so this is worth looking at.
    }

    // --- A few breeds, so the silhouettes can be compared.
    for breed in [CatBreed.maineCoon, .siamese, .persian, .munchkin, .sphynx, .britishShorthair] {
        let rig = buildCat(BreedPresets.appearance(for: breed))
        let animator = CatAnimator(rig: rig)
        var motion = CatMotion()
        motion.position = .zero
        motion.pose = .standing
        for _ in 0..<200 { animator.update(dt: 1.0 / 60, motion: motion) }
        CatBuilder.syncPose(rig)
        shot("breed-\(breed.rawValue)", rig.root,
             eye: SIMD3<Float>(x: 1.0, y: 0.22, z: 0.10), target: SIMD3<Float>(x: 0, y: 0.16, z: 0),
             fov: 34, size: (420, 320))
    }

    // --- The room, from exactly where the player sits.
    var cal = Calendar(identifier: .gregorian)
    cal.timeZone = TimeZone(identifier: "UTC")!
    var comps = DateComponents(); comps.year = 2026; comps.month = 5; comps.day = 12; comps.hour = 11
    let sky = WorldClock.sky(at: cal.date(from: comps)!, timeZone: TimeZone(identifier: "UTC")!)
    let room = RoomBuilder.build(sky: sky)

    let catRig = buildCat(BreedPresets.appearance(for: .domesticShorthair))
    let catAnim = CatAnimator(rig: catRig)
    var catMotion = CatMotion()
    catMotion.pose = .sittingTall
    catMotion.position = SIMD3<Float>(x: 0.1, y: 0, z: -0.3)
    catMotion.yaw = deg(170)
    for _ in 0..<200 { catAnim.update(dt: 1.0 / 60, motion: catMotion) }

    let world = Entity()
    world.addChild(room.root)
    world.addChild(catRig.root)

    let eye = RoomLayout.cameraPosition
    let aim = SIMD3<Float>(x: eye.x, y: eye.y + tanf(RoomLayout.cameraPitch), z: eye.z - 1)
    // The app pins the field of view to the horizontal axis at 54°; this rasteriser
    // takes a vertical FOV, so convert for a 390x844 portrait frame.
    let horizontal: Float = 54
    let aspect: Float = 390.0 / 844.0
    let vertical = 2 * atanf(tanf(horizontal * .pi / 180 / 2) / aspect) * 180 / .pi
    shot("room-player-view", world, eye: eye, target: aim, fov: vertical, size: (390, 844),
         bg: (0.05, 0.06, 0.09))
    shot("room-overhead", world,
         eye: SIMD3<Float>(x: 0.2, y: 3.4, z: 2.6), target: SIMD3<Float>(x: 0, y: 0.3, z: -0.6),
         fov: 60, size: (600, 480), bg: (0.05, 0.06, 0.09))

    // --- The cat where it sits when called over, checked against the HUD.
    // The bottom bar, status line and home indicator together occupy roughly the
    // lowest 150 pt of an 844 pt frame; the cat has to stay clear of that.
    let closeRig = buildCat(BreedPresets.appearance(for: .domesticShorthair))
    let closeAnim = CatAnimator(rig: closeRig)
    var closeMotion = CatMotion()
    closeMotion.pose = .sittingTall
    closeMotion.position = RoomLayout.playerLapSpot
    // Same facing the brain gives a cat that has come over to be petted.
    closeMotion.yaw = yawTowards(from: RoomLayout.playerLapSpot, to: RoomLayout.cameraPosition)
    for _ in 0..<200 { closeAnim.update(dt: 1.0 / 60, motion: closeMotion) }

    let closeWorld = Entity()
    closeWorld.addChild(RoomBuilder.build(sky: sky).root)
    closeWorld.addChild(closeRig.root)
    shot("room-cat-called-over", closeWorld, eye: eye, target: aim,
         fov: vertical, size: (390, 844), bg: (0.05, 0.06, 0.09))

    // The head is what the player actually looks at, and it must be completely
    // clear. The whole-body box is reported too, but a tail tip that sprawls
    // toward the camera and slips under the bar is not worth moving the cat for.
    let hudTop: Float = 844 - 150
    // The head is a bone on the modelled cat and carries no geometry of its own,
    // so measuring "is the head behind the HUD" from its mesh finds nothing and
    // prints a confident "not on screen". Ask the skinned surface instead when the
    // joint has nothing to measure.
    let headNode: Entity = closeRig.skinnedBody ?? closeRig.head
    for (label, node) in [("head", headNode), ("whole cat", closeRig.root)] {
        guard let b = screenBounds(node, eye: eye, target: aim,
                                   fovDegrees: vertical, width: 390, height: 844) else {
            print("  \(label) at lap spot: not on screen")
            continue
        }
        let hidden = max(0, b.maxY - hudTop)
        let visible = max(0, min(b.maxY, hudTop) - b.minY)
        let fraction: Float = visible > 0 ? hidden / (hidden + visible) : 1
        print(String(format: "  %@ at lap spot: y[%.0f %.0f] x[%.0f %.0f]  %.0f%% behind the HUD (top %.0f)",
                     label as NSString, b.minY, b.maxY, b.minX, b.maxX, fraction * 100, hudTop))
    }
}

// MARK: - Material map inspection

/// Writes every surface's height, normal, roughness and occlusion map as PNGs.
///
/// The material work has no other eyes on it: CI is unavailable, and Core Graphics
/// is a no-op in the shim, so the *colour* textures cannot be inspected here at all.
/// The relief can, because it is plain arithmetic over `[Float]`, and looking at it
/// is how "the tatami has a weave" gets separated from "the tatami has noise".
///
/// Each map is written at its own resolution, tiled 2×2, so seams show up. A map
/// that does not tile announces itself immediately as a cross through the middle.
func runMapDump(outputDirectory: String) {
    let fm = FileManager.default
    try? fm.createDirectory(atPath: outputDirectory, withIntermediateDirectories: true)

    func write(_ rgba: [UInt8], size: Int, name: String) {
        // Tile 2×2 so the seam runs down the middle of the image, where it is
        // obvious, rather than around the outside where it is not.
        let w = size * 2
        var rgb = [UInt8](repeating: 0, count: w * w * 3)
        for y in 0..<w {
            for x in 0..<w {
                let src = ((y % size) * size + (x % size)) * 4
                let dst = (y * w + x) * 3
                rgb[dst] = rgba[src]
                rgb[dst + 1] = rgba[src + 1]
                rgb[dst + 2] = rgba[src + 2]
            }
        }
        let path = "\(outputDirectory)/\(name).png"
        writePNG(rgb, width: w, height: w, to: path)
        print("  \(name).png  \(w)×\(w)")
    }

    func heightBytes(_ f: HeightField) -> [UInt8] {
        var out = [UInt8](repeating: 255, count: f.size * f.size * 4)
        for i in 0..<(f.size * f.size) {
            let g = UInt8(min(max(f.samples[i] * 255, 0), 255))
            out[i * 4] = g; out[i * 4 + 1] = g; out[i * 4 + 2] = g
        }
        return out
    }

    var specs: [(String, SurfaceMaps.Spec)] = [
        ("tatami", SurfaceMaps.tatami()),
        ("wood", SurfaceMaps.wood()),
        ("plaster", SurfaceMaps.plaster()),
        ("shoji", SurfaceMaps.shojiPaper()),
        ("fabric", SurfaceMaps.fabric()),
        ("futon", SurfaceMaps.futonCover()),
        ("sisal", SurfaceMaps.sisal()),
        ("litter", SurfaceMaps.litterSubstrate()),
    ]
    specs.append(("iris", SurfaceMaps.iris()))
    var cat = BreedPresets.appearance(for: .domesticShorthair)
    cat.seed = 4242
    specs.append(("coat-shorthair", SurfaceMaps.catCoat(cat, size: 512)))
    var persian = BreedPresets.appearance(for: .persian)
    persian.seed = 4242
    specs.append(("coat-persian", SurfaceMaps.catCoat(persian, size: 512)))

    for (name, spec) in specs {
        let f = spec.field
        write(heightBytes(f), size: f.size, name: "\(name)-height")
        write(f.normalMap(slopeScale: spec.slopeScale), size: f.size, name: "\(name)-normal")
        write(f.roughnessMap(base: spec.roughnessBase, variation: spec.roughnessVariation),
              size: f.size, name: "\(name)-roughness")
        write(f.occlusionMap(radius: spec.occlusionRadius, strength: spec.occlusionStrength),
              size: f.size, name: "\(name)-occlusion")

        print(String(format: "  %@: %d px/m, tilt %.1f° (asked %.1f°), relief %.2f mm",
                     name as NSString, Int(spec.relief.texelsPerMetre),
                     f.measuredRMSTilt(slopeScale: spec.slopeScale), spec.tiltDegrees,
                     spec.reliefMetres * 1000))
    }
}
